### ISSUE TITLE
File causing endless loop

### ISSUE THREAD

**Issue by laufhannes** [mrihtar/Garmin-FIT#19]
We got a file resulting in an endless loop: [endless-loop.zip](https://github.com/mrihtar/Garmin-FIT/files/3013934/endless-loop.zip)

I'm not sure what's wrong with the file, as Garmin's `FitToCSV.bat` can't convert it:
```
FIT CSV Tool - Protocol 2.0 Profile 20.81 Release
Exception in thread "main" java.lang.RuntimeException: com.garmin.fit.FitRuntim
Exception: FIT decode error: Endian 118 not supported. Error at byte: 242
        at com.garmin.fit.csv.CSVTool.run(CSVTool.java:238)
        at com.garmin.fit.csv.CSVTool.main(CSVTool.java:324)
Caused by: com.garmin.fit.FitRuntimeException: FIT decode error: Endian 118 not
supported. Error at byte: 242
        at com.garmin.fit.Decode.read(Decode.java:770)
        at com.garmin.fit.Decode.resume(Decode.java:371)
        at com.garmin.fit.Decode.read(Decode.java:348)
        at com.garmin.fit.csv.CSVTool.run(CSVTool.java:212)
        ... 1 more
```

Still, having an endless loop crashes the whole process. The following patch fixes the issue for us:
```perl
diff --git a/Garmin/FIT.pm b/Garmin/FIT.pm
--- a/call/perl/Garmin/FIT.pm
+++ b/call/perl/Garmin/FIT.pm
@@ -7608,7 +7608,7 @@ sub fetch {
       $desc_i = ($rechd & $rechd_mask_cth_local_message_type) >> $rechd_offset_cth_local_message_type;
     }
     elsif ($rechd & $rechd_mask_definition_message) {
-      $self->fetch_definition_message;
+      $self->fetch_definition_message || return undef;
     }
     else {
       $desc_i = $rechd & $rechd_mask_local_message_type;
@@ -7621,7 +7621,7 @@ sub fetch {
       my $desc = $self->data_message_descriptor->[$desc_i];
 
       if (ref $desc eq 'HASH') {
-        $self->fetch_data_message($desc);
+        $self->fetch_data_message($desc) || return undef;
       }
       else {
         $self->error(sprintf("%d at %ld: not defined", $rechd, $j));
```

**Comment by mrihtar** [comment]
Thanks for the patch - I included it in the repository. Your FIT file in the attached zip is corrupted though. At the end it has some clear text from some diving report (check in any binary editor). File could be "damaged" during export or because of a bad block on a disk.
